'use strict';
const $=id=>document.getElementById(id), E=BrainEngine, P=ConnectEngine;
const colours=[['#dcecf2','#123e58'],['#e1e8c9','#607b2a'],['#e1dff2','#6a5ca4'],['#f4dfd0','#b67146'],['#cee9e9','#15828a'],['#f5e9c5','#9e7822'],['#e7dfef','#81638e'],['#d8e7db','#3e775c']];
const extra=[['Sun','<circle cx="20" cy="20" r="7"/><path d="M20 3v5m0 24v5M3 20h5m24 0h5M8 8l4 4m16 16 4 4M8 32l4-4m16-16 4-4"/>'],['Wave','<path d="M4 12c5-8 9 8 16 0s11 8 16 0M4 21c5-8 9 8 16 0s11 8 16 0M4 30c5-8 9 8 16 0s11 8 16 0"/>'],['Cup','<path d="M7 15h22v13a8 8 0 0 1-8 8h-6a8 8 0 0 1-8-8ZM29 17h3a5 5 0 0 1 0 10h-3M12 5v5m7-5v5m7-5v5"/>']];
const icons=ICONS.concat(extra),svg=v=>'<svg aria-hidden="true" viewBox="0 0 40 42">'+icons[v][1]+'</svg>',tone=v=>'--bg:'+colours[v][0]+';--fg:'+colours[v][1];
let mode='',generation=0,timer=null,timers=new Set(),match=null,path=null,memory=null;
function later(ms){return new Promise(resolve=>{const id=setTimeout(()=>{timers.delete(id);resolve();},ms);timers.add(id);});}
function best(key,value,lower=false){try{const previous=Number(localStorage.getItem('dbfl-brain-'+key));if(value!==undefined&&(!previous||(lower?value<previous:value>previous)))localStorage.setItem('dbfl-brain-'+key,value);return Number(localStorage.getItem('dbfl-brain-'+key))||0;}catch{return 0;}}
const clock=n=>Math.floor(n/60)+':'+String(n%60).padStart(2,'0');
function stop(){generation++;clearInterval(timer);timer=null;/* stale async work exits via generation guards */}
function result(title,body){$('result').hidden=false;$('result').innerHTML='<h3>'+title+'</h3><p>'+body+'</p>';}
function status(text){$('status').textContent=text;}
function stats(a,b,c){$('stats').innerHTML=[a,b,c].map(([label,value])=>'<div class="stat"><span>'+label+'</span><strong>'+value+'</strong></div>').join('');}
function game(which){stop();mode=which;$('home').hidden=true;$('game').hidden=false;$('result').hidden=true;$('hint').hidden=which!=='path';$('undo').hidden=which!=='path';$('restart').textContent='Start again';$('board').className='board';
 const config={match:['MATCH & UNWIND','Match & Unwind','Swap neighbouring icons to make a row or column of three or more. Tap two icons or swipe an icon.','<label for="matchMode">Play mode</label><select id="matchMode"><option value="timed">60-second challenge</option><option value="calm">Untimed play</option></select>'],path:['FIND YOUR PATH','Find Your Path','Start at 1. Connect the numbers in order using every square once. Move up, down, left or right. Tap squares or drag; retrace to undo.','<label for="difficulty">Grid</label><select id="difficulty"><option value="5">Gentle · 5 × 5</option><option value="6">Medium · 6 × 6</option><option value="7">Tricky · 7 × 7</option></select>'],memory:['MEMORY MOMENT','Memory Moment','Turn over two tiles at a time. Find all eight matching pairs. There’s no time limit.','<span>Eight pairs · take your time</span>']}[which];
 $('tag').textContent=config[0];$('title').textContent=config[1];$('instructions').textContent=config[2];$('settings').innerHTML=config[3];$('start').hidden=false;$('restart').hidden=true;$('hint').disabled=true;$('undo').disabled=true;
 if(which==='match'){$('matchMode').onchange=()=>prepareMatch();prepareMatch();}else if(which==='path'){$('difficulty').onchange=()=>preparePath();preparePath();}else prepareMemory();$('game').focus();
}
function home(){stop();mode='';$('home').hidden=false;$('game').hidden=true;document.querySelector('[data-game="match"]').focus();}
function start(){if(mode==='match')startMatch();if(mode==='path')startPath();if(mode==='memory')startMemory();$('start').hidden=true;$('restart').hidden=false;}
function restart(){const which=mode;stop();$('result').hidden=true;if(which==='match'){prepareMatch();startMatch();}else if(which==='path'){preparePath();startPath();}else{prepareMemory();startMemory();}$('start').hidden=true;$('restart').hidden=false;}
function prepareMatch(){stop();match={board:E.newBoard(),score:0,left:60,active:false,busy:false,selected:-1,timed:$('matchMode').value==='timed',ending:false};drawMatch();matchStats();status('Ready when you are. Press Start to play.');$('start').hidden=false;$('restart').hidden=true;$('result').hidden=true;}
function matchStats(){stats(['Time',match.timed?match.left+' s':'No limit'],['Points',match.score],['Your best',best(match.timed?'match-timed':'match-calm')]);}
function startMatch(){match.active=true;drawMatch();status('Choose two neighbouring icons to swap.');if(match.timed){const began=Date.now();timer=setInterval(()=>{match.left=Math.max(0,60-Math.floor((Date.now()-began)/1000));matchStats();if(!match.left){clearInterval(timer);match.active=false;match.ending=true;if(!match.busy)endMatch();}},150);}}
function endMatch(){match.active=false;best(match.timed?'match-timed':'match-calm',match.score);matchStats();drawMatch();status('Take a breath. Try again whenever you like.');result('Nicely connected!',match.score+' points in 60 seconds. Every little break counts.');}
function drawMatch(){const host=$('board');host.className='board match-board';host.innerHTML=match.board.map((v,i)=>'<button type="button" class="token match-tile'+(i===match.selected?' selected':'')+'" style="'+tone(v)+'" aria-label="'+icons[v][0]+', row '+(Math.floor(i/5)+1)+', column '+(i%5+1)+'" '+(!match.active||match.busy?'disabled':'')+' data-cell="'+i+'">'+svg(v)+'</button>').join('');host.querySelectorAll('button').forEach(b=>b.onclick=()=>selectMatch(Number(b.dataset.cell)));}
async function selectMatch(i){if(!match.active||match.busy)return;if(match.selected<0){match.selected=i;drawMatch();return;}const a=match.selected;match.selected=-1;if(a===i){drawMatch();return;}if(!E.adjacent(a,i,5)){match.selected=i;drawMatch();return;}await swapMatch(a,i);}
async function swapMatch(a,b){if(!match.active||match.busy)return;const run=generation;match.busy=true;match.selected=-1;[match.board[a],match.board[b]]=[match.board[b],match.board[a]];drawMatch();await later(180);if(run!==generation)return;let cleared=E.matches(match.board);if(!cleared.length){[match.board[a],match.board[b]]=[match.board[b],match.board[a]];status('That swap doesn’t make a match. Try another pair.');match.busy=false;drawMatch();if(match.ending)endMatch();return;}
 let chain=0;while(cleared.length&&chain<30){chain++;const points=cleared.length*10*chain;match.score+=points;matchStats();status(chain>1?'A chain reaction! +'+points+' points.':'Match made! +'+points+' points.');cleared.forEach(i=>$('board').querySelector('[data-cell="'+i+'"]').classList.add('clearing'));const bubble=document.createElement('div');bubble.className='popup';bubble.textContent='+'+points;$('board').append(bubble);await later(350);if(run!==generation)return;match.board=E.refill(match.board,cleared);drawMatch();await later(180);if(run!==generation)return;cleared=E.matches(match.board);}
 if(cleared.length||!E.canMove(match.board)){match.board=E.newBoard();status('Fresh icons! The board has been reshuffled.');}match.busy=false;best(match.timed?'match-timed':'match-calm',match.score);drawMatch();if(match.ending)endMatch();else matchStats();
}
let swipe=null;
$('board').addEventListener('pointerdown',e=>{if(mode==='match'&&match.active&&!match.busy){const b=e.target.closest('[data-cell]');if(b)swipe={i:Number(b.dataset.cell),x:e.clientX,y:e.clientY};}if(mode==='path'&&path.active){const b=e.target.closest('[data-cell]');if(b){path.drag=true;movePath(Number(b.dataset.cell));}}});
$('board').addEventListener('pointermove',e=>{if(mode==='path'&&path.active&&path.drag){e.preventDefault();const b=document.elementFromPoint(e.clientX,e.clientY)?.closest('.path-tile');if(b)movePath(Number(b.dataset.cell));}});
document.addEventListener('pointerup',e=>{if(mode==='path'&&path)path.drag=false;if(mode==='match'&&swipe){const s=swipe;swipe=null;const dx=e.clientX-s.x,dy=e.clientY-s.y;if(Math.max(Math.abs(dx),Math.abs(dy))>22){const target=s.i+(Math.abs(dx)>Math.abs(dy)?(dx>0?1:-1):(dy>0?5:-5));if(target>=0&&target<30&&E.adjacent(s.i,target,5)){e.preventDefault();suppressClick=Date.now()+350;swapMatch(s.i,target);}}}});
let suppressClick=0;$('board').addEventListener('click',e=>{if(mode==='match'&&Date.now()<suppressClick){e.stopImmediatePropagation();e.preventDefault();}},true);
document.addEventListener('pointercancel',()=>{swipe=null;if(path)path.drag=false;});
let puzzleSerial=0;
function preparePath(){stop();const size=Number($('difficulty').value);path={puzzle:P.createPuzzle('DBFL-wellness-'+size+'-'+Date.now()+'-'+puzzleSerial++,size),cells:[],active:false,hints:0,drag:false};drawPath();pathStats();status('Press Start, then choose checkpoint 1.');$('start').hidden=false;$('restart').hidden=true;$('result').hidden=true;$('hint').disabled=true;$('undo').disabled=true;}
function pathStats(){stats(['Squares',path.cells.length+' / '+path.puzzle.size**2],['Next number',Math.min(path.puzzle.checkpoints.length,path.cells.reduce((n,i)=>path.puzzle.lookup[i]?path.puzzle.lookup[i]+1:n,1))],['Hints',path.hints]);}
function startPath(){path.active=true;drawPath();$('hint').disabled=false;status('Start at 1. Tap or drag through neighbouring squares.');}
function drawPath(){const host=$('board'),size=path.puzzle.size;host.className='board path-board';host.style.setProperty('--size',size);host.innerHTML=Array.from({length:size*size},(_,i)=>{const n=path.puzzle.lookup[i];return '<button type="button" class="path-tile'+(path.cells.includes(i)?' traced':'')+(i===path.cells.at(-1)?' end':'')+'" data-cell="'+i+'" aria-label="Row '+(Math.floor(i/size)+1)+', column '+(i%size+1)+(n?', checkpoint '+n:'')+(path.cells.includes(i)?', on your path':'')+'" '+(!path.active?'disabled':'')+'>'+(n?'<span class="checkpoint">'+n+'</span>':'')+'</button>';}).join('');host.querySelectorAll('button').forEach(b=>b.onclick=()=>movePath(Number(b.dataset.cell)));$('undo').disabled=!path.active||!path.cells.length;}
function movePath(i){if(!path.active||i===path.cells.at(-1))return;const r=P.extendPath(path.puzzle,path.cells,i);if(r.error){status(r.error);return;}path.cells=r.path;drawPath();pathStats();status('Keep connecting. Retrace any part of your path to undo it.');if(r.won){path.active=false;path.drag=false;drawPath();$('hint').disabled=true;$('undo').disabled=true;result('You found your path!',path.puzzle.size**2+' squares connected'+(path.hints?' with '+path.hints+' hint'+(path.hints===1?'':'s'):'')+'. Take a moment to enjoy it.');status('Try another puzzle whenever you’re ready.');}}
function hint(){if(mode!=='path'||!path.active)return;const solution=path.puzzle.solution;let common=0;while(common<path.cells.length&&path.cells[common]===solution[common])common++;path.hints++;if(common<path.cells.length){path.cells=path.cells.slice(0,common);drawPath();pathStats();status('Your path was trimmed back to a route we know can finish. Press Hint again for the next square.');}else{movePath(solution[path.cells.length]);pathStats();if(path.active)status('One helpful step. You can continue from here.');}}
function prepareMemory(){stop();memory={deck:E.shuffle([...Array(8).keys(),...Array(8).keys()]),open:[],matched:new Set(),moves:0,active:false,busy:false};drawMemory();memoryStats();status('Press Start to reveal the tiles.');$('start').hidden=false;$('restart').hidden=true;$('result').hidden=true;}
function memoryStats(){stats(['Pairs',memory.matched.size/2+' / 8'],['Turns',memory.moves],['Fewest turns',best('memory',undefined,true)||'—']);}
function startMemory(){memory.active=true;drawMemory();status('Choose two tiles. Find the matching pair.');}
function drawMemory(){const host=$('board');host.className='board memory-board';host.innerHTML=memory.deck.map((v,i)=>{const open=memory.open.includes(i)||memory.matched.has(i);return '<button type="button" class="memory-tile'+(open?' open':'')+(memory.matched.has(i)?' matched':'')+'" style="'+tone(v)+'" data-cell="'+i+'" aria-label="Tile '+(i+1)+(open?', '+icons[v][0]:', face down')+(memory.matched.has(i)?', matched':'')+'" '+(!memory.active||memory.busy||open?'disabled':'')+'>'+(open?svg(v):'<span aria-hidden="true">✦</span>')+'</button>';}).join('');host.querySelectorAll('button').forEach(b=>b.onclick=()=>flip(Number(b.dataset.cell)));}
async function flip(i){if(!memory.active||memory.busy||memory.open.includes(i)||memory.matched.has(i))return;memory.open.push(i);drawMemory();if(memory.open.length<2)return;memory.moves++;memory.busy=true;memoryStats();drawMemory();const run=generation;await later(750);if(run!==generation)return;const [a,b]=memory.open;if(memory.deck[a]===memory.deck[b]){memory.matched.add(a);memory.matched.add(b);status('A pair found!');}else status('Remember those icons and try another pair.');memory.open=[];memory.busy=false;if(memory.matched.size===16){memory.active=false;best('memory',memory.moves,true);result('All pairs found!',memory.moves+' turns. A little focus, a little fun.');status('Try again for a fresh set of tiles.');}drawMemory();memoryStats();}
$('board').addEventListener('keydown',e=>{const b=e.target.closest('[data-cell]');if(!b)return;const cols=mode==='match'?5:mode==='path'?path.puzzle.size:4;const delta={ArrowLeft:-1,ArrowRight:1,ArrowUp:-cols,ArrowDown:cols}[e.key];if(delta!==undefined){e.preventDefault();const i=Number(b.dataset.cell),next=i+delta;if(next<0||!E.adjacent(i,next,cols))return;$('board').querySelector('[data-cell="'+next+'"]')?.focus();}});
document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>game(b.dataset.game));$('back').onclick=home;$('start').onclick=start;$('restart').onclick=restart;$('hint').onclick=hint;$('undo').onclick=()=>{if(path?.active){path.cells.pop();drawPath();pathStats();status('One step undone.');}};
$('match-art').innerHTML='<div class="mini-icons">'+[0,1,4,2,3,0,4,1,2].map(v=>'<span class="token" style="'+tone(v)+'">'+svg(v)+'</span>').join('')+'</div>';
const entry=location.hash.slice(1);if(['match','path','memory'].includes(entry))game(entry);
